server:
  port: ${PORT:5000}
korail:
  service-key: ${KORAIL_SERVICE_KEY}
bus:
  service-key: ${BUS_SERVICE_KEY}
kakao:
  api-key: ${KAKAO_API_KEY}
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
       add-mappings: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 86400000
